Setup logging functions

diff --git a/install b/install
--- a/install
+++ b/install
@@ -36,26 +36,27 @@ while getopts ":g:r:t:h" opt; do
       show_help $0
       ;;
     \?)
-      echo "ERROR invalid option: -$OPTARG" >&2
+      log "ERROR invalid option: -$OPTARG" >&2
       exit 1
       ;;
     :)
-      echo "ERROR option -$OPTARG requires an argument." >&2
+      log "ERROR option -$OPTARG requires an argument." >&2
       exit 1
       ;;
   esac
 done
 
 ## Give one last chance to back out
-read -p \
-"Installing NixOS into $root_mount ($root_type) and GRUB into $grub_device;
-continue? [yn] " -n 1 -r
+log_start "Installing NixOS into $root_mount ($root_type) \
+and GRUB into $grub_device; continue? [yn] "
+read -n 1 -r
 echo
 if [[ ! $REPLY =~ ^[Yy]$ ]]
 then
-  echo "exiting; nothing was harmed"
+  log "exiting; nothing was harmed"
   exit 1
 fi
+exit
 
 iso=latest-iso-minimal-x86_64-linux
 if [ ! -d host/nix/store ];
@@ -76,6 +77,7 @@ $here/stage1 $here $root_mount $root_type $grub_device
 ## TODO: Clean up mounts
 
 ## Installation is complete
-read -p "reboot into NixOS now? [yn] " -n 1 -r
+log_start "Reboot into NixOS now? [yn] "
+read -n 1 -r
 echo
 [[ $REPLY =~ ^[Yy]$ ]] && reboot
diff --git a/util b/util
--- a/util
+++ b/util
@@ -1,27 +1,32 @@
-#!/bin/bash
+#!/bin/sh
 
 set -eu
 
-function check_existence
+check_existence()
 {
   set +e
   which $1 > /dev/null 2>&1
   exists=$?
   if [ ! "$exists" -eq "0" ];
   then
-    echo "$1 not found; see the README for dependencies" 1>&2
+    log "$1 not found; see the README for dependencies" 1>&2
     exit 1
   fi
   set -e
 }
 
-function show_help
+show_help()
 {
-  echo "usage: $0 [OPTION...]"
-  echo
-  echo "  -h  Show this help message"
-  echo "  -g  Set GRUB target device (default: $grub_device)"
-  echo "  -r  Set root filesystem target device (default: $root_mount)"
-  echo "  -t  Set root filesystem type (default: $root_type)"
+  log "usage: $0 [OPTION...]"
+  log
+  log "  -h  Show this help message"
+  log "  -g  Set GRUB target device (default: $grub_device)"
+  log "  -r  Set root filesystem target device (default: $root_mount)"
+  log "  -t  Set root filesystem type (default: $root_type)"
   exit 1
 }
+
+log()
+{ printf ">>> $@\n"; }
+log_start()
+{ printf ">>> $@"; }
