Clean up some logging

diff --git a/util b/util
--- a/util
+++ b/util
@@ -9,7 +9,7 @@ check_existence()
   exists=$?
   if [ ! "$exists" -eq "0" ];
   then
-    log "$1 not found; see the README for dependencies" 1>&2
+    log_end "$1 not found; see the README for dependencies" 1>&2
     exit 1
   fi
   set -e
